const CREATURES = [
  // ─── TIER 1 ──────────────────────────────────────────────────────────────────
  {
    id: 1, name: 'Emberpup', type1: 'Fire', type2: null, tier: 1, rarity: 'Common',
    base_atk: 38, base_def: 22, base_spd: 45, base_hp: 65,
    skill_name: 'Ember Bite', skill_description: 'A fiery bite that may burn the target.',
    skill_multiplier: 2.0, skill_status_effect: 'burn',
    zone: 'Ashveil Crater', evolves_from: null, evolves_to_a: 9, evolves_to_b: null,
    description: 'A small fiery pup with ember-tipped paws.',
  },
  {
    id: 2, name: 'Aquafin', type1: 'Water', type2: null, tier: 1, rarity: 'Common',
    base_atk: 32, base_def: 35, base_spd: 50, base_hp: 70,
    skill_name: 'Aqua Slash', skill_description: 'A razor-sharp water blade.',
    skill_multiplier: 2.1, skill_status_effect: null,
    zone: 'Tidehaven Depths', evolves_from: null, evolves_to_a: 10, evolves_to_b: null,
    description: 'A swift aquatic creature with crystalline fins.',
  },
  {
    id: 3, name: 'Galesprout', type1: 'Wind', type2: null, tier: 1, rarity: 'Common',
    base_atk: 35, base_def: 18, base_spd: 60, base_hp: 55,
    skill_name: 'Gust Flurry', skill_description: 'A rapid flurry of wind strikes.',
    skill_multiplier: 2.0, skill_status_effect: null,
    zone: 'Stormspire Peak', evolves_from: null, evolves_to_a: 11, evolves_to_b: null,
    description: 'A sprightly sprout that rides wind currents.',
  },
  {
    id: 4, name: 'Stoneback', type1: 'Earth', type2: null, tier: 1, rarity: 'Common',
    base_atk: 28, base_def: 55, base_spd: 18, base_hp: 80,
    skill_name: 'Rock Slam', skill_description: 'A devastating ground slam.',
    skill_multiplier: 2.2, skill_status_effect: 'stun',
    zone: 'Sunstone Plateau', evolves_from: null, evolves_to_a: 12, evolves_to_b: null,
    description: 'A tortoise-like creature with a stone shell.',
  },
  {
    id: 5, name: 'Voltkit', type1: 'Thunder', type2: null, tier: 1, rarity: 'Common',
    base_atk: 42, base_def: 20, base_spd: 55, base_hp: 58,
    skill_name: 'Static Shock', skill_description: 'Paralyzes the target with electricity.',
    skill_multiplier: 2.0, skill_status_effect: 'paralyze',
    zone: 'Stormspire Peak', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A crackling electric foxling.',
  },
  {
    id: 6, name: 'Frostling', type1: 'Ice', type2: null, tier: 1, rarity: 'Common',
    base_atk: 30, base_def: 30, base_spd: 35, base_hp: 68,
    skill_name: 'Ice Shard', skill_description: 'Pelts the enemy with ice shards.',
    skill_multiplier: 2.0, skill_status_effect: null,
    zone: 'Umbral Rift', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A tiny ice sprite trailing frost.',
  },
  {
    id: 7, name: 'Shadowpup', type1: 'Shadow', type2: null, tier: 1, rarity: 'Common',
    base_atk: 40, base_def: 25, base_spd: 48, base_hp: 60,
    skill_name: 'Shadow Claw', skill_description: 'Strikes from the shadows to silence the foe.',
    skill_multiplier: 2.1, skill_status_effect: 'silence',
    zone: 'Umbral Rift', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A pup of pure shadow with glowing eyes.',
  },
  {
    id: 8, name: 'Glimlet', type1: 'Light', type2: null, tier: 1, rarity: 'Common',
    base_atk: 33, base_def: 28, base_spd: 42, base_hp: 62,
    skill_name: 'Radiant Burst', skill_description: 'A burst of holy light.',
    skill_multiplier: 2.0, skill_status_effect: null,
    zone: 'Sunstone Plateau', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A glimmering sprite of pure light energy.',
  },

  // ─── TIER 2 ──────────────────────────────────────────────────────────────────
  {
    id: 9, name: 'Infernog', type1: 'Fire', type2: null, tier: 2, rarity: 'Common',
    base_atk: 58, base_def: 35, base_spd: 62, base_hp: 95,
    skill_name: 'Inferno Blast', skill_description: 'Unleashes a torrent of fire. Causes burn.',
    skill_multiplier: 2.2, skill_status_effect: 'burn',
    zone: 'Ashveil Crater', evolves_from: 1, evolves_to_a: 13, evolves_to_b: 14,
    description: 'A molten hound whose fur is living flame.',
  },
  {
    id: 10, name: 'Torrentail', type1: 'Water', type2: null, tier: 2, rarity: 'Common',
    base_atk: 50, base_def: 55, base_spd: 70, base_hp: 100,
    skill_name: 'Torrent Surge', skill_description: 'A crushing wave attack.',
    skill_multiplier: 2.1, skill_status_effect: null,
    zone: 'Tidehaven Depths', evolves_from: 2, evolves_to_a: 15, evolves_to_b: 16,
    description: 'A powerful water serpent with a crashing tail.',
  },
  {
    id: 11, name: 'Cyclomane', type1: 'Wind', type2: null, tier: 2, rarity: 'Common',
    base_atk: 55, base_def: 30, base_spd: 80, base_hp: 80,
    skill_name: 'Cyclone Edge', skill_description: 'A spinning blade of compressed air.',
    skill_multiplier: 2.0, skill_status_effect: null,
    zone: 'Stormspire Peak', evolves_from: 3, evolves_to_a: 17, evolves_to_b: null,
    description: 'A maned beast that generates cyclones.',
  },
  {
    id: 12, name: 'Ramrock', type1: 'Earth', type2: null, tier: 2, rarity: 'Common',
    base_atk: 42, base_def: 75, base_spd: 22, base_hp: 110,
    skill_name: 'Seismic Charge', skill_description: 'Charges and causes an earthquake-like shockwave.',
    skill_multiplier: 2.3, skill_status_effect: 'stun',
    zone: 'Sunstone Plateau', evolves_from: 4, evolves_to_a: null, evolves_to_b: null,
    description: 'A towering stone ram that shakes the earth.',
  },

  // ─── TIER 3 ──────────────────────────────────────────────────────────────────
  {
    id: 13, name: 'Blazehorn', type1: 'Fire', type2: 'Earth', tier: 3, rarity: 'Rare',
    base_atk: 88, base_def: 75, base_spd: 45, base_hp: 150,
    skill_name: 'Magma Charge', skill_description: 'A devastating molten charge that burns.',
    skill_multiplier: 2.3, skill_status_effect: 'burn',
    zone: 'Ashveil Crater', evolves_from: 9, evolves_to_a: 21, evolves_to_b: null,
    description: 'A volcanic bull with magma-filled horns.',
  },
  {
    id: 14, name: 'Cinderfox', type1: 'Fire', type2: 'Wind', tier: 3, rarity: 'Rare',
    base_atk: 90, base_def: 35, base_spd: 99, base_hp: 110,
    skill_name: 'Ember Gale', skill_description: 'A cyclone of cinders that burns.',
    skill_multiplier: 2.2, skill_status_effect: 'burn',
    zone: 'Ashveil Crater', evolves_from: 9, evolves_to_a: 21, evolves_to_b: null,
    description: 'A blazing fox that leaves a trail of embers on the wind.',
  },
  {
    id: 15, name: 'Tidalwyrm', type1: 'Water', type2: 'Earth', tier: 3, rarity: 'Rare',
    base_atk: 70, base_def: 95, base_spd: 30, base_hp: 160,
    skill_name: 'Tidal Crush', skill_description: 'An ocean-pressure crush that stuns.',
    skill_multiplier: 2.4, skill_status_effect: 'stun',
    zone: 'Tidehaven Depths', evolves_from: 10, evolves_to_a: 22, evolves_to_b: null,
    description: 'A massive sea wyrm armored in living coral.',
  },
  {
    id: 16, name: 'Mistshade', type1: 'Water', type2: 'Wind', tier: 3, rarity: 'Rare',
    base_atk: 75, base_def: 55, base_spd: 85, base_hp: 125,
    skill_name: 'Mist Veil', skill_description: 'Shrouds enemies in disorienting mist, causing silence.',
    skill_multiplier: 2.1, skill_status_effect: 'silence',
    zone: 'Tidehaven Depths', evolves_from: 10, evolves_to_a: 22, evolves_to_b: null,
    description: 'A spectral water-wind being that fades into fog.',
  },
  {
    id: 17, name: 'Zephyrax', type1: 'Wind', type2: 'Thunder', tier: 3, rarity: 'Rare',
    base_atk: 85, base_def: 40, base_spd: 95, base_hp: 115,
    skill_name: 'Thunder Gale', skill_description: 'Lightning-fast wind strike that may paralyze.',
    skill_multiplier: 2.2, skill_status_effect: 'paralyze',
    zone: 'Stormspire Peak', evolves_from: 11, evolves_to_a: 23, evolves_to_b: null,
    description: 'A crackling wind raptor trailing lightning.',
  },
  {
    id: 18, name: 'Poisonmaw', type1: 'Poison', type2: 'Nature', tier: 3, rarity: 'Rare',
    base_atk: 80, base_def: 50, base_spd: 65, base_hp: 135,
    skill_name: 'Venom Bloom', skill_description: 'Releases toxic spores that burn.',
    skill_multiplier: 2.0, skill_status_effect: 'burn',
    zone: 'Sunstone Plateau', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A venomous plant-beast with necrotic jaws.',
  },
  {
    id: 19, name: 'Psyclaw', type1: 'Psychic', type2: 'Shadow', tier: 3, rarity: 'Rare',
    base_atk: 82, base_def: 45, base_spd: 75, base_hp: 120,
    skill_name: 'Mind Rend', skill_description: 'Tears at the mind, silencing the target.',
    skill_multiplier: 2.1, skill_status_effect: 'silence',
    zone: 'Umbral Rift', evolves_from: null, evolves_to_a: 24, evolves_to_b: null,
    description: 'A psychic predator with shadow-wreathed claws.',
  },
  {
    id: 20, name: 'Ironfang', type1: 'Metal', type2: 'Earth', tier: 3, rarity: 'Rare',
    base_atk: 75, base_def: 90, base_spd: 38, base_hp: 145,
    skill_name: 'Iron Bite', skill_description: 'A crushing metallic bite.',
    skill_multiplier: 2.3, skill_status_effect: 'stun',
    zone: 'Sunstone Plateau', evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'A metal-plated predator with drill-like fangs.',
  },

  // ─── TIER 4 — LEGENDARY ──────────────────────────────────────────────────────
  {
    id: 21, name: 'Infernus Rex', type1: 'Fire', type2: 'Earth', tier: 4, rarity: 'Legendary',
    base_atk: 150, base_def: 110, base_spd: 95, base_hp: 230,
    skill_name: 'Volcanic Wrath', skill_description: 'A cataclysmic eruption that burns all foes.',
    skill_multiplier: 2.4, skill_status_effect: 'burn',
    zone: null, evolves_from: 13, evolves_to_a: 25, evolves_to_b: null,
    description: 'The undying king of ash and magma.',
  },
  {
    id: 22, name: 'Abyssalord', type1: 'Water', type2: 'Earth', tier: 4, rarity: 'Legendary',
    base_atk: 130, base_def: 130, base_spd: 80, base_hp: 255,
    skill_name: 'Abyss Torrent', skill_description: 'Drags foes into crushing ocean depths.',
    skill_multiplier: 2.3, skill_status_effect: 'stun',
    zone: null, evolves_from: 15, evolves_to_a: 25, evolves_to_b: null,
    description: 'Lord of the deep, encased in abyssal coral.',
  },
  {
    id: 23, name: 'Stormbinder', type1: 'Wind', type2: 'Thunder', tier: 4, rarity: 'Legendary',
    base_atk: 155, base_def: 70, base_spd: 140, base_hp: 210,
    skill_name: 'Storm Sovereign', skill_description: 'Commands a storm to paralyze all enemies.',
    skill_multiplier: 2.4, skill_status_effect: 'paralyze',
    zone: null, evolves_from: 17, evolves_to_a: 25, evolves_to_b: null,
    description: 'The eternal tempest made flesh.',
  },
  {
    id: 24, name: 'Voidmind', type1: 'Psychic', type2: 'Shadow', tier: 4, rarity: 'Legendary',
    base_atk: 160, base_def: 85, base_spd: 120, base_hp: 220,
    skill_name: 'Void Collapse', skill_description: 'Collapses reality around the target, silencing them.',
    skill_multiplier: 2.4, skill_status_effect: 'silence',
    zone: 'Umbral Rift', evolves_from: 19, evolves_to_a: 25, evolves_to_b: null,
    description: 'A mind that devoured itself and became the void.',
  },

  // ─── TIER 5 — APEX ───────────────────────────────────────────────────────────
  {
    id: 25, name: 'Primordius', type1: 'Fire', type2: 'Water', tier: 5, rarity: 'Apex',
    base_atk: 220, base_def: 200, base_spd: 180, base_hp: 400,
    skill_name: 'Primordial Surge', skill_description: 'Channels all elemental forces into a single devastating strike.',
    skill_multiplier: 2.5, skill_status_effect: 'burn',
    zone: null, evolves_from: null, evolves_to_a: null, evolves_to_b: null,
    description: 'The first creature — source of all elemental power, shattered and reborn.',
  },
];

module.exports = { CREATURES };
